version: '3.3'
services:
  dbserver:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    #      PGDATA: "/var/lib/postgresql/data/pgdata"
    #    volumes:
    #      - "c:/prog-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind=0.0.0.0
      -client=0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500
  proxy:
    image: traefik:3.0.4
    command: |
      --api.insecure=true
      --providers.consulCatalog
      --providers.consulCatalog.exposedByDefault=false
      --providers.consulCatalog.endpoint.address=consul:8500
      --providers.consulCatalog.refreshInterval=10s
    expose:
      - 80
    depends_on:
      - consul
  clientes-service:
    image: app-clientes
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HTTP_PORT: 8080
    #    ports:
    #      - "8080:8080"
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  productos-service:
    image: app-productos
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1
  orden-compra-service:
    image: app-ordencompras
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuida
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      QUARKUS_HTTP_PORT: 8080
    depends_on:
      - dbserver
      - consul
    deploy:
      replicas: 1